# Generated by Django 5.2.7 on 2025-10-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='3 Months', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='AR Online Quran Academy', max_length=100),
        ),
    ]
